### ISSUE TITLE
Improved sensible-docs

### ISSUE THREAD

**Issue by CodeFromAnywhere** [Code-From-Anywhere/sensible#20]
- [ ] get sensible-docs to run on localhost with new data format
- [ ] add warning in Safari if CRUD problems (with instructions to solve this or to move to supported browsers)
- [ ] Create possibility to CRUD markdown files in repo (makes it possible to alter docs from within the sensible docs UX)
- [ ] Make sure not to expose an endpoint/type twice
- [ ] Docs menu: When a category is empty, don’t show it
- [ ] Links: New section in docs: Link to GitHub places: code, issues, pr’s, branches, project board for now, later make it possible to extend/edit this, but this is the default convention. Github repo can be taken from package.json file. Also link to website and other stuff. Just add it to CoreConstants.

**Comment by Karsens** [comment]
moved to md
