### ISSUE TITLE
Week 19 Todo

### ISSUE THREAD

**Issue by CodeFromAnywhere** [Code-From-Anywhere/sensible#48]
Other
- [x] meeting with Suyog and Umid about `md fs crud` (video)
- [x] review guilhermes pr (video)
- [x] make `npx change-json [json-path] key1.key2.[index/latest/push].key3 "value"` (video) [issue](https://github.com/Code-From-Anywhere/change-json/issues/1)

Sensible
- [x] add `sensible setup`, which just executes the [cfa-workspace command](https://github.com/Code-From-Anywhere/cfa-workspace) #32 
- [x] merge web and doc together, use docusaurus and call it "web"
- [x] #43 
- [ ] work on docs, trailer and walkthrough @Karsens 
- [ ] POC fs md crud app @suyogpahadi
- [ ] fix windows support @grrbm 
- [ ] deploy POC of Sensible VSCode Extension @umidg 
- [ ] fix linux support @bhagyasah 
- [ ] do demos @brunabaudel @karsens

Discuss:
- Can king become open source?
- CoworkSurf open source?
