### ISSUE TITLE
Week 20 Todo

### ISSUE THREAD

**Issue by CodeFromAnywhere** [Code-From-Anywhere/sensible#50]
Marketing @Karsens 
- [ ] run king again, make it scrape
- [ ] create script against my king network data to filter taglines and create labels with it
- [ ] create issue about creating king SDK (or do it myself if it's easy)
- [ ] message all developers about sensible demo (you can book me link in second message)

King Store @Karsens 
- [ ] install linux on other mac
- [ ] migrate to markdown storage https://github.com/Code-From-Anywhere/king/issues/114

Further Improvements @Karsens 
- [ ] improve init: `gh cli` for automatic repo creation
- [ ] `sensible ship` should ask to `turbo build`, ask to `puball packages`, then ship
- [ ] learn about beta for npm packages and start using that for non-live changes

**Comment by CodeFromAnywhere** [comment]
moved to ~/Documents
